# Generated by Django 6.0.2 on 2026-04-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_detail_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',)},
        ),
    ]
