# Generated by Django 6.0.2 on 2026-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_content_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicesection',
            new_name='services_se_service_dc9624_idx',
            old_name='services_se_service_790fa8_idx',
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
    ]
